export const ObjectTypes = {
  ARRAY: 'Array',
  BLOB: 'Blob',
  UINT8_ARRAY: 'Uint8Array',
  UINT16_ARRAY: 'Uint16Array',
  UINT32_ARRAY: 'Uint32Array',
  ARRAY_BUFFER: 'ArrayBuffer',
  BOOLEAN: 'Boolean',
  FUNCTION: 'Function',
  NULL: 'Null',
  NUMBER: 'Number',
  OBJECT: 'Object',
  STRING: 'String',
  UNDEFINED: 'Undefined',
  UNKNOWN: 'Unknown',
};
